### ISSUE TITLE
Adding to Android freezes VS for a minute or so.

### ISSUE THREAD

**Issue by Inrego** [interisti/vs-material-icons-generator#10]
### Installed product versions
- Visual Studio: VS Community 2017 v15.4.0
- This extension: 1.4

### Description
When adding an icon to my Android project, VS freezes for about a full minute before I gain control again.

### Steps to recreate
1. Create Xamarin Android project
2. Right click project to add icon
3. Find an icon, and add to project
4. Wait and see

### Current behavior
It's adding about 5 files to the project, and I wouldn't guess it should take so long? Adding to iOS is almost instantaneous, and that's 3 files.

**Comment by AmrAlSayed0** [comment]
This a "issue" with visual studio itself because whenever the Resources folder is modified, visual studio automatically updates Resources.Designer.cs file. Depending on how many icons you already have added, it can take some time.

I am confused as to why is it hanging when it is a new project created.

**Comment by ckaiman** [comment]
Same issue: Same versions as above.

I have a lot of icons, and VS has been hanging for over 15 minutes.  I will have to kill the process soon.
