### ISSUE TITLE
Sizes not found but do exist at material.io for images

### ISSUE THREAD

**Issue by LeoJHarris** [interisti/vs-material-icons-generator#23]
Hi there not sure exactly where your source of images are coming from but I was unable to get some images at sizes I did manage to get from material.io. 

Unable to get the size from extension
![capture](https://user-images.githubusercontent.com/5468757/40812014-c68c2d80-6587-11e8-82f8-f5368f0f54f2.PNG)

Was able to download the size from material.io 
![capture2](https://user-images.githubusercontent.com/5468757/40812074-157907ba-6588-11e8-80d8-f8905de13eb0.PNG)

I guess is it possible to get a wider net of sizes that match i.e. https://material.io?

Thanks! Extension is great though very helpful

**Comment by interisti** [comment]
Hi,

All this extension does is to call a url to get a list of icons (same as material.io calls) then construct url to download it from their github repo. Before they updated the site, icons were match, but after upgrade there are some icons that does not exist in some sizes or does not exist at all. So that error message was a quick fix actually, until i find some other solution.

Maybe better option would be to get that zip file and extract icons from there.

**Comment by jstun** [comment]
interisti,
I'm having an issue that I believe is related to this as well. I'm getting a buffer error in VS. Here is the stack trace from Windows Event Viewer:

![image](https://user-images.githubusercontent.com/21327045/42127833-7981703e-7c6d-11e8-8191-00c3d8ce83ef.png)


I was trying to retrieve the following image: ic_radio_button_checked_black_18dp

![image](https://user-images.githubusercontent.com/21327045/42127846-de5ddcf4-7c6d-11e8-98d4-5a9b1909a025.png)

**Comment by interisti** [comment]
I've reverted back source to https://material.io/tools/icons/static/data.json and some of the icons are now displayed, though there are several which does not exist in google's repo.

So i'm closing this for now
