### ISSUE TITLE
VS 2019 hangs when icon added

### ISSUE THREAD

**Issue by MaticBabnik** [interisti/vs-material-icons-generator#37]
### Installed product versions
- Visual Studio: 2019 community
- This extension: 1.8

### Description
When I add an icon to solution it freezes.

### Steps to recreate
1. Open a xamarin android project.
2. Open plugin.
3. Add an icon.

### Current behavior
It focking crashes my IDE.

### Expected behavior
Not crash. (the icon is added when I relaunch)

**Comment by michalss** [comment]
well same here it would begreat if someone can fix it...

**Comment by interisti** [comment]
Hey,

I've just published the V2 version which should fix any VS19 issues. can you try it and reopen this if its still an issue.

Thanks.

**Comment by michalss** [comment]
I just tested and it works much better, however still taking a bit time to download, but im not sure if this is fixable or not..

**Comment by interisti** [comment]
well i've put those icons behind cloudflare (couldn't use github repo cause of adding themes) and it might take time to cache those icons, i guess. plus plugin downloads icons one by one instead of doing it in parallel so that might also contribute to "slow adding". 

anyways, glad that weird VS19 bug is fixed and thanks for testing.
P.S. if you have any suggestions i'll be glad if you create an issue. 
cheers.
